
DROP SEQUENCE USERS_SEQ;
DROP SEQUENCE SECTION_SEQ;
DROP SEQUENCE COURSE_SECTION_SEQ;
DROP SEQUENCE SCHEDULE_SEQ;



 CREATE SEQUENCE USERS_SEQ
 START WITH     501
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 CREATE SEQUENCE SECTION_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 CREATE SEQUENCE COURSE_SECTION_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 CREATE SEQUENCE SCHEDULE_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

