
DROP SEQUENCE ENOBLE.USERS_SEQ;
DROP SEQUENCE ENOBLE.SECTION_SEQ;
DROP SEQUENCE ENOBLE.COURSE_SECTION_SEQ;
DROP SEQUENCE ENOBLE.SCHEDULE_SEQ;



 CREATE SEQUENCE ENOBLE.USERS_SEQ
 START WITH     501
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 CREATE SEQUENCE ENOBLE.SECTION_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 CREATE SEQUENCE ENOBLE.COURSE_SECTION_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 CREATE SEQUENCE ENOBLE.SCHEDULE_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

